[workspace]
resolver = "2"
members = [
    "channel_access_token",
    "insight",
    "lib",
    "liff",
    "manage_audience",
    "messaging_api",
    "module",
    "module_attach",
    "shop",
    "webhook",
]
